const ACTION_TYPES  = {
GET_TRIP_REQUEST:"GET_TRIP_REQUEST",
GET_TRIP_SUCCESS:"GET_TRIP_SUCCESS",
GET_TRIP_ERROR:"GET_TRIP_ERROR",

CREATE_TRIP_REQUEST:"CREATE_TRIP_REQUEST",
CREATE_TRIP_SUCCESS:"CREATE_TRIP_SUCCESS",
CREATE_TRIP_ERROR:"CREATE_TRIP_ERROR",

UPDATE_TRIP_REQUEST:"UPDATE_TRIP_REQUEST",
UPDATE_TRIP_SUCCESS:"UPDATE_TRIP_SUCCESS",
UPDATE_TRIP_ERROR:"UPDATE_TRIP_ERROR",

DELETE_TRIP_REQUEST:"DELETE_TRIP_REQUEST",
DELETE_TRIP_SUCCESS:"DELETE_TRIP_SUCCESS",
DELETE_TRIP_ERROR:"DELETE_TRIP_ERROR",
}

export default ACTION_TYPES;